### ISSUE TITLE
Kata created by myjinxin2015 "inspired" by other sites

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#42]
Author: [myjinxin2015](https://www.codewars.com/users/myjinxin2015)

### Codesignal

Note: In order to view the problem on codesignal you've to register on the website.

- [ ] [Simple Fun #1: Seats in Theater](https://www.codewars.com/kata/588417e576933b0ec9000045) | [Seats in Theater
](https://app.codesignal.com/arcade/code-arcade/intro-gates/bszFiQAog96G9CXKg)
- [ ] [Simple Fun #2: Circle of Numbers](https://www.codewars.com/kata/58841cb52a077503c4000015) | [circleOfNumbers](https://app.codesignal.com/arcade/code-arcade/intro-gates/vExYvcGnFsEYSt8nQ)
- [ ] [Simple Fun #3: Late Ride](https://www.codewars.com/kata/588422ba4e8efb583d00007d) | [lateRide](https://app.codesignal.com/arcade/code-arcade/intro-gates/aiKck9MwwAKyF8D4L)
- [ ] [Simple Fun #4: Phone Call](https://www.codewars.com/kata/588425ee4e8efb583d000088) | [Phone Call](https://app.codesignal.com/arcade/code-arcade/intro-gates/mZAucMXhNMmT7JWta)
- [ ] [Simple Fun #5: Knapsack Light](https://www.codewars.com/kata/58842a2b4e8efb92b7000080) | [knapsackLight](https://app.codesignal.com/arcade/intro/level-9/r9azLYp2BDZPyzaG2)
- [ ] [Simple Fun #6: Is Infinite Process?](https://www.codewars.com/kata/588431bb76933b84520000d3) | [Is Infinite Process?
](https://app.codesignal.com/arcade/code-arcade/at-the-crossroads/aFF9HDm2Rsti9j5kc)
- [ ] [Simple Fun #7: Will You?](https://www.codewars.com/kata/58844a13aa037ff143000072) | [Will You?](https://app.codesignal.com/arcade/code-arcade/at-the-crossroads/jZ4ZSiGohzFTeg4yb)
- [ ] [Simple Fun #8: Kill K-th Bit](https://www.codewars.com/kata/58844f1a76933b1cd0000023/) | [Kill k-th bit](https://app.codesignal.com/arcade/code-arcade/corner-of-0s-and-1s/b5z4P2r2CGCtf8HCR/)
- [ ] [Simple Fun #9: Array Packing](https://www.codewars.com/kata/588453ea56daa4af920000ca) | [Array Packing](https://app.codesignal.com/arcade/code-arcade/corner-of-0s-and-1s/b5z4P2r2CGCtf8HCR/)
- [ ] [Simple Fun #10: Range Bit Counting](https://www.codewars.com/kata/58845748bd5733f1b300001f) | [Range Bit Count](https://app.codesignal.com/arcade/code-arcade/corner-of-0s-and-1s/b5z4P2r2CGCtf8HCR/)
- [ ] [Simple Fun #11: Swap Adjacent Bits](https://www.codewars.com/kata/58845a92bd573378f4000035) | [Swap Adjacent Bits](https://app.codesignal.com/arcade/code-arcade/corner-of-0s-and-1s/b5z4P2r2CGCtf8HCR/)
- [ ] [Simple Fun #29: Is MAC48 Address?](https://www.codewars.com/kata/5886faac54a7111c21000072) | [isMAC48Address](https://app.codesignal.com/arcade/intro/level-10/HJ2thsvjL25iCvvdm)
- [ ] [Simple Fun #35: Different Squares](https://www.codewars.com/kata/588805ca44c7e8c3a100013c) | [differentSquares](https://app.codesignal.com/arcade/intro/level-12/fQpfgxiY6aGiGHLtv)
- [ ] [Simple Fun #41: Elections Winners](https://www.codewars.com/kata/58881b859ab1e053240000cc) | [electionWinner](https://app.codesignal.com/arcade/intro/level-10/8RiRRM3yvbuAd3MNg)
- [ ] [Simple Fun #42: Are Similar?](https://www.codewars.com/kata/588820169ab1e053240000e0) | [areSimilar](https://app.codesignal.com/arcade/intro/level-4/xYXfzQmnhBvEKJwXP)
- [ ] [Simple Fun #64: Almost Increasing Sequence](https://www.codewars.com/kata/5893e7578afa367a61000036) | [almostIncreasingSequence](https://app.codesignal.com/arcade/intro/level-2/2mxbGwLzvkTCKAJMG)
- [ ] [Simple Fun #65: Matrix Elements Sum](https://www.codewars.com/kata/5893eb36779ce5faab0000da) | [matrixElementsSum](https://app.codesignal.com/arcade/intro/level-2/xskq4ZxLyqQMCLshr)
- [ ] [Simple Fun #67: Array Change](https://www.codewars.com/kata/5893f43b779ce54da4000124) | [arrayChange](https://app.codesignal.com/arcade/intro/level-4/xvkRbxYkdHdHNCKjg)
- [ ] [Simple Fun #68: Palindrome Rearranging](https://www.codewars.com/kata/5893fa478a8a23ef82000031) | [palindromeRearranging](https://app.codesignal.com/arcade/intro/level-4/Xfeo7r9SBSpo3Wico)
- [ ] [Simple Fun #69: Are Equally Strong?](https://www.codewars.com/kata/5894017082b9fb62c50000df) | [areEquallyStrong](https://app.codesignal.com/arcade/intro/level-5/g6dc9KJyxmFjB98dL)
- [ ] [Simple Fun #70: Avoid Obstacles](https://www.codewars.com/kata/5894045b8a8a230d0c000077) | [avoidObstacles](https://app.codesignal.com/arcade/intro/level-5/XC9Q2DhRRKQrfLhb5)
- [ ] [Simple Fun #72: Absolute Values Sum Minimization](https://www.codewars.com/kata/589414918afa367b4800015c) | [absoluteValuesSumMinimization](https://app.codesignal.com/arcade/intro/level-7/ZFnQkq9RmMiyE6qtq)  
- [x] (in beta) [Simple Fun #73: Strings Rearrangement](https://www.codewars.com/kata/58941b1ec5d31ac28300007f) | [stringsRearrangment](https://app.codesignal.com/arcade/intro/level-7/PTWhv2oWqd6p4AHB9)
- [ ] [Simple Fun #74: Growing Plant](https://www.codewars.com/kata/58941fec8afa3618c9000184) | [growingPlant](https://app.codesignal.com/arcade/intro/level-9/xHvruDnQCx7mYom3T)
- [ ] [Simple Fun #75: Digit Degree](https://www.codewars.com/kata/589422431a88082ea600002a) | [digitDegree](https://app.codesignal.com/arcade/intro/level-9/hoLtYWbjdrD2PF6yo)
- [ ] [Simple Fun #77: Is Beautiful String?](https://www.codewars.com/kata/58942c43c5d31a77eb0000ea)| [isBeautifulString](https://app.codesignal.com/arcade/intro/level-10/PHSQhLEw3K2CmhhXE)
- [ ] [Simple Fun #78: Build Palindrome](https://www.codewars.com/kata/58942f9175f2c78f4b000108) | [buidPalindrome](https://app.codesignal.com/arcade/intro/level-10/ppZ9zSufpjyzAsSEx)
- [ ] [Simple Fun #79: Delete a Digit](https://www.codewars.com/kata/5894318275f2c75695000146) | [deleteDigit](https://app.codesignal.com/arcade/intro/level-11/vpfeqDwGZSzYNm2uX)
- [ ] [Simple Fun #81: Digits Product](https://www.codewars.com/kata/589436311a8808bf560000f9) | [digitsProduct](https://app.codesignal.com/arcade/intro/level-12/NJJhENpgheFRQbPRA)
- [ ] [Simple Fun #83: MineSweeper](https://www.codewars.com/kata/58952e29f0902eae8b0000cb) | [Minesweeper](https://app.codesignal.com/arcade/intro/level-5/ZMR5n7vJbexnLrgaM)
- [ ] [Simple Fun #84: Box Blur](https://www.codewars.com/kata/5895326bcc949f496b00003e) | [boxBlur](https://app.codesignal.com/arcade/intro/level-5/5xPitc3yT3dqS7XkP)
- [ ] [Simple Fun #85: Polygon Perimeter](https://www.codewars.com/kata/58953a5a41c97914d7000070) | [Polygon Perimeter](https://app.codesignal.com/arcade/code-arcade/waterfall-of-integration/L7KWEYbPoornGyf7K)
- [ ] [Simple Fun #86: is Information Consistent?](https://www.codewars.com/kata/58956f5ff780edf4a70000a2) | [Is Information Consistent?](https://app.codesignal.com/arcade/code-arcade/waterfall-of-integration/jkuhbNn7AdeCC7z7R)
- [ ] [Simple Fun #87: Shuffled Array](https://www.codewars.com/kata/589573e3f0902e8919000109) | [Shuffled Array](https://app.codesignal.com/arcade/code-arcade/sorting-outpost/s4BEFMcpLdGbjX9KX)
- [ ] [Simple Fun #88: Sort By Height](https://www.codewars.com/kata/589577f0d1b93ae32a000001) | [sortByHeight](https://app.codesignal.com/arcade/intro/level-3/D6qmdBL2NYz49XHwM)
- [ ] [Simple Fun #89: Boxes Packing](https://www.codewars.com/kata/58957c5041c979cf9e00002f) | [Boxes Packing](https://app.codesignal.com/arcade/code-arcade/sorting-outpost/9y4wLpcqnNozn92tG)
- [ ] [Simple Fun #90: Rows Rearranging](https://www.codewars.com/kata/58958ef541c9794213000090) | [Rows Rearranging](https://app.codesignal.com/arcade/code-arcade/sorting-outpost/vuXQuYFReJPe6hHAf)
- [ ] [Simple Fun #91: Unique Digit Products](https://www.codewars.com/kata/5897d94dd07028546c00009d) | [Unique Digit Products](https://app.codesignal.com/arcade/code-arcade/sorting-outpost/oY6FASrCMEqkxwcAC)
- [ ] [Simple Fun #92: Digit Difference Sort](https://www.codewars.com/kata/5897df29fcc4b9c310000030) | [digit difference sort](https://app.codesignal.com/arcade/code-arcade/sorting-outpost/2SFFWqkhkqC7mMBse)
---
- [x] [Chess Fun #1: Chess Board Cell Color](https://www.codewars.com/kata/5894134c8afa3618c9000146) | [chessBoardCellColor](https://app.codesignal.com/arcade/intro/level-6/t97bpjfrMDZH8GJhi)
- [x] [Chess Fun #2: Bishop And Pawn](https://www.codewars.com/kata/589425c2561a35dd1a0000a2) | [bishopAndPawn](https://app.codesignal.com/arcade/intro/level-9/6M57rMTFB9MeDeSWo)
- [x] [Chess Fun #3: Chess Knight](https://www.codewars.com/kata/589433358420bf25950000b6) | [chessKnight](https://app.codesignal.com/arcade/intro/level-11/pwRLrkrNpnsbgMndb)
- [x] [Chess Fun #4: Bishop Diagonal](https://www.codewars.com/kata/5897e394fcc4b9c310000051) | [Bishop diagonal](https://app.codesignal.com/arcade/code-arcade/chess-tavern/wGLCfzpdcA2o9kSpD)
- [x] [Chess Fun #5: Whose Turn?](https://www.codewars.com/kata/5897e572948beb7858000089) | [Whose Turn?](https://app.codesignal.com/arcade/code-arcade/chess-tavern/SJRNgqggTaktuCJGj)
- [x] [Chess Fun #6: Chess Bishop Dream](https://www.codewars.com/kata/5897ea323387497f460001a0) | [Chess Bishop Dream](https://app.codesignal.com/arcade/code-arcade/chess-tavern/FfjPkYvo9ah6wgXem)
- [x] [Chess Fun #7: Chess Triangle](https://www.codewars.com/kata/5897eebff3d21495a70000df) | [Chess Triangle](https://app.codesignal.com/arcade/code-arcade/chess-tavern/NhRZQrrMqeWYL9L9Z)
- [x] [Chess Fun #8: Amazon Checkmate](https://www.codewars.com/kata/5897f30d948beb78580000b2) | [Amazon Checkmate](https://app.codesignal.com/arcade/code-arcade/chess-tavern/3hvEEqS7wuoEMZJJC)
---
- [x] [Challenge Fun #1: Contours Shifting](https://www.codewars.com/kata/589536a01dd837c5f000010a) | [Contours Shifting](https://app.codesignal.com/arcade/code-arcade/waterfall-of-integration/LfP67YRDw2rxoLmeP)
- [x] [Challenge Fun #2: Gravitation](https://www.codewars.com/kata/58954096f780edd09a0001ce) | [Gravitation](https://app.codesignal.com/arcade/code-arcade/waterfall-of-integration/hqrYesGKEaKQnv7Sv)
- [x] [Challenge Fun #3: Correct Nonogram](https://www.codewars.com/kata/58954c4fd1b93a19520000c8) | [Correct Nonogram](https://app.codesignal.com/arcade/code-arcade/waterfall-of-integration/TTsQFn3ppXCk9uTXs)
- [x] [Challenge Fun #4: Maximum Sum](https://www.codewars.com/kata/589584c0f780ed726b0000c8) | [Maximum Sum](https://app.codesignal.com/arcade/code-arcade/sorting-outpost/64koZSDqndwYxFZj6)

### LeetCode

 - [x] [Trapping Rain Water](https://www.codewars.com/kata/583daf5f8bbc0446f50002d0/) | [Trapping Rain Water](https://leetcode.com/problems/trapping-rain-water/)

**Comment by error256** [comment]
Did anyone check if he actually isn't the author of the tasks?

**Comment by hobovsky** [comment]
Maybe being the author is not the only relevant thing here?

I think it's possible that the way how problems are licensed in one system could forbid submitting the same problem somewhere else, isn't it?

**Comment by error256** [comment]
> I think it's possible that the way how problems are licensed in one system could forbid submitting the same problem somewhere else, isn't it?

If it's rules of another site, it doesn't have to do anything with anyone expect the author and that site. If they signed it legally, which is very unlikely and too much to assume by default, my understanding is that transferring exclusive rights usually ends up in situations too complicated to understand even for lawyers. (I could ask the same way, what if the other sites copied the problems and made it look like they were published there earlier than here. That's not impossible either, but rather improbable for well-known sites.)

**Comment by Blind4Basics** [comment]
> Did anyone check if he actually isn't the author of the tasks?

how? I don't see the name of the author of the challenges, there.

Note: looks like a lot of those links are dead => ?

**Comment by error256** [comment]
Also, should trivial katas be marked here somehow? For example, "Kill K-th Bit" already has the task in its name and it's trivial, so it should be fine if the story is removed from the description.

**Comment by farhan443** [comment]
What does the checkmarks mean?

**Comment by XRFXLP** [comment]
> What does the checkmarks mean?

@farhan443 : Those kata have been handled, and they''ve been retired now.

> Note: looks like a lot of those links are dead => ?

@Blind4Basics : No, they're not. On codesignal, problems gets incrementally unlocked (that is: next level can only be unlocked if the last level has been completed(or one can unlock it paying some "points/coins").
As of now, the only link that was dead for me was [Is infinite process?](https://app.codesignal.com/arcade/code-arcade/at-the-crossroads/jZ4ZSiGohzFTeg4yb):

![image](https://user-images.githubusercontent.com/23459568/143404807-4f505d3b-635c-4da1-853e-2daf82905c81.png)

Because, I've not completed the problem 11:
![image](https://user-images.githubusercontent.com/23459568/143404884-5cea1894-7c4c-4a02-bf14-0a507f6bc68d.png)


---
Some more to add though:
1. [Simple Fun #30: Strings Construction](https://www.codewars.com/kata/58870402c81516bbdb000088)
2. [Simple Fun #31: Is Substitution Cipher?](https://www.codewars.com/kata/58870742c815166a960000af)
3. [Simple Fun #32: Create Anagram](https://www.codewars.com/kata/5887099cc815166a960000c6)
4. [Simple Fun #33: Construct Square](https://www.codewars.com/kata/58870c87c81516bbdb0000d8)
5. [Simple Fun #34: Numbers Grouping](https://www.codewars.com/kata/588711735ea0b4649e000001)
6. [Simple Fun #36: Most Frequent Digit Sum](https://www.codewars.com/kata/588809279ab1e0e17700002e)
2. [Simple Fun #37: House Numbers sum](https://www.codewars.com/kata/58880c6e79a0a3e459000004) | [House Numbers sum](https://app.codesignal.com/arcade/code-arcade/well-of-integration/3QMXNwGfvLMoQwed7)
2. [Simple Fun #38: House of Cats](https://www.codewars.com/kata/588810c99fb63e49e1000606) | [House of Cats](https://app.codesignal.com/arcade/code-arcade/well-of-integration/RaWLwT2eb96hp4N5Z)
3. [Simple Fun #39: Switch Lights](https://www.codewars.com/kata/5888145122fe8620950000f0/javascript) | [Switch Lights](https://app.codesignal.com/arcade/code-arcade/well-of-integration/x3ix7CY93z2bwKDtG)
4. [Simple Fun #40: Timed Reading](https://www.codewars.com/kata/588817db5fb13af14a000020) | [Timed Reading](https://app.codesignal.com/arcade/code-arcade/well-of-integration/mJr7vgtN4X4ecL7ZA)
5. [Simple Fun #43: Ada Number](https://www.codewars.com/kata/58882bdb5edef0343400002a) | [Ada number](https://app.codesignal.com/arcade/code-arcade/well-of-integration/Ghe6HWhFft8h6fR49)
6. [Simple Fun #44: Three Split](https://www.codewars.com/kata/588833be1418face580000d8) | [Three Split](https://app.codesignal.com/arcade/code-arcade/well-of-integration/QmK8kHTyKqh8xDoZk)
7. [Simple Fun #45: New Numeral System](https://www.codewars.com/kata/5888445107a0d57711000032/javascript) | [New Numeral System](https://app.codesignal.com/arcade/code-arcade/lab-of-transformations/ngQTG9kra7GE9pnnK)
8. [Simple Fun #46: Cipher 26](https://www.codewars.com/kata/588847702ffea657ba00001b) | [Cipher 26](https://app.codesignal.com/arcade/code-arcade/lab-of-transformations/JeDDnToFtitiiWDZn)
9. [Simple Fun #47: Stolen Lunch](https://www.codewars.com/kata/58884a65f06a3d3bef000049) | [Stolen Lunch](https://app.codesignal.com/arcade/code-arcade/lab-of-transformations/M97sbwRp3tGy8uAb8)
10. [Simple Fun #48: Higher Version](https://www.codewars.com/kata/58884e352ffea6d2f8000082) | [Higher Version](https://app.codesignal.com/arcade/code-arcade/lab-of-transformations/vsKRjYKv4SCjzJc8r)
11. [Simple Fun #49: Decipher](https://www.codewars.com/kata/5888514674b58e929a000036) | [Decipher](https://app.codesignal.com/arcade/code-arcade/lab-of-transformations/dB9drnfWzpiWznESA)
12. [Simple Fun #50: Array Conversion](https://www.codewars.com/kata/588854201361435f5e0000bd)
13. [Simple Fun #51: Array Previous Less](https://www.codewars.com/kata/588856a82ffea640c80000cc)
14. [Simple Fun #52: Pair Of Shoes](https://www.codewars.com/kata/58885a7bf06a3d466e0000e3)
15. [Simple Fun #53: Combs](https://www.codewars.com/kata/58898b50b832f8046a0000ec)
16. [Simple Fun #54: Strings Crossover](https://www.codewars.com/kata/5889902f53ad4a227100003f)
17. [Simple Fun #55: Cyclic String](https://www.codewars.com/kata/58899594b832f80348000122)
18. [Simple Fun #56: Beautiful Text](https://www.codewars.com/kata/58899b0c97630e0b70000089)
19. [Simple Fun #57: Runners Meetings](https://www.codewars.com/kata/5889a0706069af1cb9000176)
20. [Simple Fun #58: Volleyball Positions](https://www.codewars.com/kata/5889f08eb71a7dcee600006c)
21. [Simple Fun #59: Reverse On Diagonals](https://www.codewars.com/kata/5889a6b653ad4a22710000d0)
22. [Simple Fun #60: Swap Diagonals](https://www.codewars.com/kata/5889a8b335de69cc620000c8)
23. [Simple Fun #61: Crossing Sum](https://www.codewars.com/kata/5889ab4928c08c08da00009b)
24. [Simple Fun #62: Draw Rectangle](https://www.codewars.com/kata/5889ae4f7af7f99a9a000019)
25. [Simple Fun #63: Shape Area](https://www.codewars.com/kata/5893e0c41a88085c330000a0/javascript) | [shapeArea](https://app.codesignal.com/arcade/intro/level-2/yuGuHvcCaFCKk56rJ)
26. [Simple Fun #82: Star Rotation](https://www.codewars.com/kata/58943e3e8a8a238752000118)

For simple 30 - 36: [Relevent collection link](https://app.codesignal.com/arcade/code-arcade/mirror-lake)
![image](https://user-images.githubusercontent.com/23459568/143422348-e0cb53d9-9410-4249-b3da-e33c29c58f6c.png)

For Simple fun 50 - 57: [Relevent collection link](https://app.codesignal.com/arcade/code-arcade/spring-of-integration/)
![image](https://user-images.githubusercontent.com/23459568/143418385-1681ae66-a9d0-4201-9ae5-f30c357ca774.png)

For Simple fun 58 - 62 and simple fun 82: [Relevent collection link](https://app.codesignal.com/arcade/code-arcade/list-backwoods)
![image](https://user-images.githubusercontent.com/23459568/143419386-4e1c69a6-eb9e-48b3-8011-7657ef06743b.png)


Good Luck :upside_down_face: !

**Comment by Voileexperiments** [comment]
> > I think it's possible that the way how problems are licensed in one system could forbid submitting the same problem somewhere else, isn't it?
> 
> If it's rules of another site, it doesn't have to do anything with anyone expect the author and that site. If they signed it legally, which is very unlikely and too much to assume by default, my understanding is that transferring exclusive rights usually ends up in situations too complicated to understand even for lawyers. (I could ask the same way, what if the other sites copied the problems and made it look like they were published there earlier than here. That's not impossible either, but rather improbable for well-known sites.)

Usually community-contributed problems are licensed by something like CC BY-SA, and the author owns the right of the written problem.

Besides, the author *always* have the right to re-license their original work on other sites (unless exclusive rights were obtained), so this usually isn't a problem. Of course, the author violating the license of an existing problem in the first place is another issue...

**Comment by MobulaKuhlii** [comment]
[Simple Fun #85: Polygon Perimeter](https://www.codewars.com/kata/58953a5a41c97914d7000070) can be safely retired, it's already a duplicate of [Land perimeter.](https://www.codewars.com/kata/5839c48f0cf94640a20001d3)

**Comment by mjpieters** [comment]
[Wood Cut](https://www.codewars.com/kata/583dbc028bbc0446f500032b) was a LintCode.com problem (no longer listed). Here's a [web archive copy from 18 months before the kata was created](https://web.archive.org/web/20150614094234/https://www.lintcode.com/en/problem/wood-cut/).
